### PR TITLE
Solved Hoax Number Kata

### PR DESCRIPTION
**Pull request by rahulchanglani**
## Details
**Issue you fixed:** #918 

**Issue you added:** #919

**Name of the function you implemented**: isHoaxNumber

**Name of the function you added test cases for**: maskDebitCard

## Checklist (won't be merged if they are not all ticked)
- [x] I have asked for this issue, and was assigned it
- [x] I have properly filled the "Details" section above  :arrow_up:
- [x] I didn't modify any test case  :red_circle:
- [x] I have implemented the function and all its tests pass  :white_check_mark:
- [x] I have added a new test case for someone to implement  :new:
- [x] I have created an issue for my new test case  :speak_no_evil:
- [x] I've :star: the repository (or not, all up to you)
- [x] And more importantly, I've had fun! :beer:

### CODE REVIEW

**Comment by rgehan** [comment]
Hey @rahulchanglani,

We cannot let you merge your PR as it doesn't pass the tests.

If you think this is a mistake, feel free to ping me in your reply.

##### This comment was automatically generated by a bot.

**Comment by rahulchanglani** [comment]
The tests are passing. I committed 4 files instead of 3 as mentioned in the rules due to which merge & CI is failing.

**Comment by rgehan** [comment]
Hey @rahulchanglani,

We cannot let you merge your PR as it doesn't pass the tests.

If you think this is a mistake, feel free to ping me in your reply.

##### This comment was automatically generated by a bot.

**Pull request closed without merging**
