### PR TITLE
Array to upper case

### PR DESCRIPTION
**Pull request by rogelio-o**
## Details
**Issue you fixed:** #856

**Issue you added:** #860

**Name of the function you implemented**: arrayToUpperCase

**Name of the function you added test cases for**: uglyNumber

## Checklist (won't be merged if they are not all ticked)
- [X] I have asked for this issue, and was assigned it
- [X ] I have properly filled the "Details" section above  :arrow_up:
- [X] I didn't modify any test case  :red_circle:
- [X] I have implemented the function and all its tests pass  :white_check_mark:
- [X] I have added a new test case for someone to implement  :new:
- [X] I have created an issue for my new test case  :speak_no_evil:
- [X] I've :star: the repository (or not, all up to you)
- [X] And more importantly, I've had fun! :beer:

### CODE REVIEW

**Comment by rogelio-o** [comment]
> ## There's a problem with your PR
> Hey **rogelio-o**,
> Please read the following log in order to understand what is the problem with
> your PR.
> 
> If there's an actual error, please fix it.
> 
> If you think this is a false-positive, or if you can justify your changes,
> please respond to this comment.
> 
> ### Node.js: node
> **./scripts/test.js**
> 
> ```
> ###################################
> ##           WARNING             ##
> ###################################
> 
> It looks like you have changed more than 3 files in this PR. Could you
> check that you only committed relevant files. For example, any file
> outputted by your IDE, or by a build tool you use is not relevant. On
> the other hand, if you fixed a test case, then it's ok.
> 
> Here are the files that you changed:
> - src/arrayToUpperCase.js (MODIFIED)
> - src/arrayToUpperCase.test.js (MODIFIED)
> - src/uglyNumber.js (NEW)
> - src/uglyNumber.test.js (NEW)
> 
> ###################################
> ##     LINTING YOUR CHANGES      ##
> ###################################
> 
> Running command: "eslint src/arrayToUpperCase.js src/arrayToUpperCase.test.js src/uglyNumber.js src/uglyNumber.test.js"
> 
> ###################################
> ##       RUNNING TEST FILE       ##
> ###################################
> 
> Running command: "jest src/arrayToUpperCase.test.js"
> 
>  PASS  src/arrayToUpperCase.test.js
>   arrayToUpperCase
>     ✓ arrayToUpperCase - strings (5ms)
>     ✓ arrayToUpperCase Null
>     ✓ arrayToUpperCase - array is not strictly composed of strings (1ms)
>     ✓ arrayToUpperCase - parameter is not an array
> 
> Test Suites: 1 passed, 1 total
> Tests:       4 passed, 4 total
> Snapshots:   0 total
> Time:        1.199s
> Ran all test suites matching /src\/arrayToUpperCase.test.js/i.
> Exiting with status: 1
> ```

expect(arrayToUpperCase(123)).toThrow(); doesn't work because is like throw new Error.

expect(() => arrayToUpperCase(123)).toThrow(); is the right way to allow toThrow method execute and check the exception.

**Comment by leodevo** [comment]
It seems I did not write my test correctly my bad @rogelio-o :/

**Comment by rogelio-o** [comment]
> It seems I did not write my test correctly my bad @rogelio-o :/

Don't worry! I'm sure @rgehan will notice soon. ;)

**Comment by rgehan** [comment]
Hey @rogelio-o,

Thanks for your contribution, your PR was merged, and your kata is now available for others to play with.

If there's been any issue with the process, please ping me in your reply.

##### This comment was automatically generated by a bot.

**Comment by rgehan** [comment]
@rogelio-o Noticed!

**Pull request merged**
