### PR TITLE
Solve twitter block message generator challenge

### PR DESCRIPTION
**Pull request by Neatoro**
## Details
**Issue you fixed:** #535

**Issue you added:** #555

**Name of the function you implemented**: twitterBlockMessageGenerator

**Name of the function you added test cases for**: isPalindrom

## Checklist (won't be merged if they are not all ticked)
- [x] I have asked for this issue, and was assigned it
- [x] I have properly filled the "Details" section above  :arrow_up:
- [ ] I didn't modify any test case  :red_circle:
- [x] I have implemented the function and all its tests pass  :white_check_mark:
- [x] I have added a new test case for someone to implement  :new:
- [x] I have created an issue for my new test case  :speak_no_evil:
- [x] I've :star: the repository (or not, all up to you)
- [x] And more importantly, I've had fun! :beer:

### CODE REVIEW

**Comment by Neatoro** [comment]
I had to adapt the tests because they were wrongly written but I did not change the test logic.

**Comment by Neatoro** [comment]
I had to adapt the tests because they were wrongly written but I did not change the test logic.

**Comment by rgehan** [comment]
Hey @Neatoro, `isPalindrom` already exists as `isPalindrome`.

Please change your kata

**Comment by Neatoro** [comment]
I have updated the kata to a different one :)

**Comment by rgehan** [comment]
Hey @Neatoro,

Thanks for your contribution, your PR was merged, and your kata is now available for others to play with.

If there's been any issue with the process, please ping me in your reply.

##### This comment was automatically generated by a bot.

**Comment by rgehan** [comment]
Sorry, @EByrdS, this kata is not merged yet (look for the "up for grabs" label) and cannot be assigned to you now.

##### This comment was automatically generated by a bot.

**Pull request merged**
