### PR TITLE
Implements subtraction

### PR DESCRIPTION
**Pull request by chgasparoto**

### CODE REVIEW

**Comment by chgasparoto** [comment]
Since is similar to sum functin, I implemented the sub :)

**Comment by TimothePearce** [comment]
gonna have some tee-shirt 🍺

**Comment by rgehan** [comment]
Hey, @TimothePearce already implemented it, you can still implement the "multiply" method if you want: https://github.com/rgehan/hacktoberfest-2k18-katas/issues/5

**Comment by rgehan** [comment]
Ping me in the issue if you want it to be assigned to you :)

**Comment by chgasparoto** [comment]
I'll do it then

**Comment by rgehan** [comment]
Hey, could you remove all the changes that are:
- not the implementation of `multiply`
- not a new test case

You should leave the implementation of sub to someone else, that's the point of the game :)

**Comment by chgasparoto** [comment]
I'll close the PR since I implemented the `multiply` :)
Thanks for the help

**Comment by chgasparoto** [comment]
Is there a way to delete this PR? I couldn't find the action to do it :(

**Pull request closed without merging**
