### PR TITLE
Implemented rotateRight and added addOdd

### PR DESCRIPTION
**Pull request by kirtansakariya**
## Details
**Issue you fixed:** #336 

**Issue you added:** #367

**Name of the function you implemented**: `rotateRight`

**Name of the function you added test cases for**: `addOdd`

## Checklist (won't be merged if they are not all ticked)
- [x] I have asked for this issue, and was assigned it
- [x] I have properly filled the "Details" section above  :arrow_up:
- [x] I didn't modify any test case  :red_circle:
- [x] I have implemented the function and all its tests pass  :white_check_mark:
- [x] I have added a new test case for someone to implement  :new:
- [x] I have created an issue for my new test case  :speak_no_evil:
- [x] I've :star: the repository (or not, all up to you)
- [x] And more importantly, I've had fun! :beer:

### CODE REVIEW

**Comment by kirtansakariya** [comment]
I had to modify the test cases from `toBe` to `toEqual` as suggested in the thread for issue #336

**Comment by kirtansakariya** [comment]
I had to modify the test cases from `toBe` to `toEqual` as suggested in the thread for issue #336

**Comment by rgehan** [comment]
If `toBe` works, leave it, else fix it

**Comment by kirtansakariya** [comment]
`toBe` tests to see if the two objects are the same. However, since the object that is passed in gets changed it does not end up being the same when it is returned. So `toBe` will return that it does not match even though I shifted it the correct amount. I just tried doing an in place shift, but that did not return true with the `toBe` method but does with the `toEqual` method.

**Comment by rgehan** [comment]
It that case, you can change that assertion in your PR! :)

**Comment by kirtansakariya** [comment]
Alright. I just ticked the `no test cases modified` item. Is that what you wanted me to do or something else? Sorry if I misinterpreted.

**Pull request merged**
