### PR TITLE
Implemented countCodeLines

### PR DESCRIPTION
**Pull request by mannutech**
## Details
**Link to the issue:** *https://github.com/rgehan/hacktoberfest-2k18-katas/issues/157*

**Name of the function you implemented**: *countCodeLines*

**Name of the function you added test cases for**: *countCodeLines*

## Checklist (won't be merged if they are not all ticked)
- [x] I have asked for this issue, and was assigned it
- [x] I have properly filled the "Details" section above  :arrow_up:
- [x] I didn't modify any test case  :red_circle:
- [x] I have implemented the function and all its tests pass  :white_check_mark:
- [x] I have added a new test case for someone to implement  :new:
- [x] I have created an issue for my new test case  :speak_no_evil:
- [x] I've :star: the repository (or not, all up to you)
- [x] And more importantly, I've had fun! :beer:

### CODE REVIEW

**Comment by mannutech** [comment]
@rgehan What is this now, I have to change test file manually as suggested by you yesterday. Now what can we do for this Travis

**Comment by rgehan** [comment]
Hey, could you rebase your PR so that it only contains the relevant changes? Alternatively you could open another PR and cherrypick your changes

**Comment by mannutech** [comment]
@rgehan Not working after rebasing .

**Comment by mannutech** [comment]
@rgehan please change line 35 of countCodeLines.test.js
It is a wrong assertion. I am quite frustrated with this now. 
expect(countCodeLines(messedUpSnippet)).toEqual(5)
Travis is always failing me

**Comment by rgehan** [comment]
Closing the PR, but you're still assigned to the issue.

Please reopen a PR with only the 3 necessary changes

**Pull request closed without merging**
