### PR TITLE
Implement slug function (and fixed slug tests), added isTruthy tests

### PR DESCRIPTION
**Pull request by whathejoe**
## Details
**Link to the issue:** *https://github.com/rgehan/hacktoberfest-2k18-katas/issues/213*

**Name of the function you implemented**: *slug*

**Name of the function you added test cases for**: *slug*

## Checklist (won't be merged if they are not all ticked)
- [x] I have asked for this issue, and was assigned it
- [x] I have properly filled the "Details" section above  :arrow_up:
- [ ] I didn't modify any test case  :red_circle:
- [x] I have implemented the function and all its tests pass  :white_check_mark:
- [x] I have added a new test case for someone to implement  :new:
- [x] I have created an issue for my new test case  :speak_no_evil:
- [x] I've :star: the repository (or not, all up to you)
- [x] And more importantly, I've had fun! :beer:

### CODE REVIEW

**Comment by rgehan** [comment]
Please add a new kata

**Comment by whathejoe** [comment]
Alright, will do. Btw I had to fix the tests for the kata I worked on, should I still check `I didn't modify any test case`?

**Comment by whathejoe** [comment]
Test script is failing because I modified `slug.test.js`

**Comment by rgehan** [comment]
I'm ok with your changes, thanks!

**Comment by whathejoe** [comment]
Np 👍 Thanks as well

**Pull request merged**
