### PR TITLE
Implement 'firstCharacterInString'

### PR DESCRIPTION
**Pull request by fritzlolpro**

### CODE REVIEW

**Comment by cptjacky** [comment]
Hey, before we can merge this, you have to create a new test case for someone else to implement.

The README will give you more info ;)

**Comment by fritzlolpro** [comment]
> Hey, before we can merge this, you have to create a new test case for someone else to implement.
> 
> The README will give you more info ;)

Hello. I've added new kata, hope I did it correctly

**Comment by andrey-semin** [comment]
I'll take this one

**Comment by rgehan** [comment]
Thank you

**Pull request merged**
