### PR TITLE
adds calcTrig function

### PR DESCRIPTION
**Pull request by TiffanieJ**
## Details
**Issue you fixed:** [#669](https://github.com/rgehan/hacktoberfest-2k18-katas/issues/669)

**Issue you added:** *link to the issue*

**Name of the function you implemented**: calculateTrig
**Name of the function you added test cases for**: pythagorean

## Checklist (won't be merged if they are not all ticked)
- [ x] I have asked for this issue, and was assigned it
- [x ] I have properly filled the "Details" section above  :arrow_up:
- [x ] I didn't modify any test case  :red_circle:
- [ x] I have implemented the function and all its tests pass  :white_check_mark:
- [ x] I have added a new test case for someone to implement  :new:
- [x ] I have created an issue for my new test case  :speak_no_evil:
- [ ] I've :star: the repository (or not, all up to you)
- [x ] And more importantly, I've had fun! :beer:

### CODE REVIEW

**Comment by rgehan** [comment]
@TiffanieJ Use the command above to merge your PR

**Comment by TiffanieJ** [comment]
merge fixed:#697 created:#732

**Comment by rgehan** [comment]
Hey @rgehan,

We cannot let you merge your PR as it seems you weren't assigned to the issue, or it simply doesn't exist.

Please double-check you provided the correct issue ID.

If you think this is a mistake, feel free to ping me in your reply.

##### This comment was automatically generated by a bot.

**Comment by rgehan** [comment]
Hey @TiffanieJ,

Thanks for your contribution, your PR was merged, and your kata is now available for others to play with.

If there's been any issue with the process, please ping me in your reply.

##### This comment was automatically generated by a bot.

**Pull request merged**
