### PR TITLE
Update totalResistanceOfParallelResistors.test.js

### PR DESCRIPTION
**Pull request by andrasbacsai**
The third test case's toEqual should be 41.45. Correcting pull request #954. Cannot continue with #953 due to this problem.

### CODE REVIEW

**Comment by andrasbacsai** [comment]
Correcting a test case because it is incorrect and I cannot finish my issue #953 .

**Comment by tenkmilan** [comment]
András is right, the toEqual of the third test case should be 41.45. 

Thank you for the correction!

**Comment by rgehan** [comment]
It seems the other PR was merged succesfully so there's no need for this fix

**Comment by andrasbacsai** [comment]
Are you sure? I still see the wrong test case in [totalResistanceOfParallelresistors.test.js](https://github.com/rgehan/hacktoberfest-2k18-katas/blob/master/src/totalResistanceOfParallelResistors.test.js).
`expect(totalResistanceOfParallelResistors(1000, 1000, 470, 100, 100)).toEqual(43.05);`

**Pull request closed without merging**
