### PR TITLE
Added implmentation for takeWhile

### PR DESCRIPTION
**Pull request by sadarshannaiynar**
### Details
**Link to the issue:** #37 

**Name of the function you implemented**: takeWhile
**Name of the function you added test cases for**: takeWhile

### Checklist
- [x] I have asked for this issue, and was assigned it
- [x] I have properly filled the "Details" section above  :arrow_up:
- [x] I didn't modify any test case  :red_circle:
- [x] I have implemented the function and all its tests pass  :white_check_mark:
- [ ] I have added a new test case for someone to implement  :new:
- [ ] I have created an issue for my new test case  :speak_no_evil:
- [x] And more importantly, I've had fun! :beer:

### CODE REVIEW

**Comment by cptjacky** [comment]
You took on that issue before we merged the PR implementing the tests.
You'll have to rebase on master & create a new test case before we can merge this!

**Comment by rgehan** [comment]
Yep, as @cptjacky said, could you:
- Rebase your PR so that there are no more conflicts
- Add a new test case

**Comment by rgehan** [comment]
@sadarshannaiynar Do you plan to complete it, or should I give the issue to someone else?

**Comment by sadarshannaiynar** [comment]
@rgehan Sure I would rebase. Sorry for the late response but it's night here.

**Comment by sadarshannaiynar** [comment]
@rgehan Closing this PR and will raise a new one.

**Pull request closed without merging**
