### PR TITLE
Find final velocity

### PR DESCRIPTION
**Pull request by xstplvivek**
## Details
**Issue you fixed:** #1047

**Issue you added:** #1058

**Name of the function you implemented**: findFinalVelocityOfAnObject

**Name of the function you added test cases for**: isCoPrime

## Checklist (won't be merged if they are not all ticked)
- [x ] I have asked for this issue, and was assigned it
- [x ] I have properly filled the "Details" section above  :arrow_up:
- [ ] I didn't modify any test case  :red_circle:
- [ x] I have implemented the function and all its tests pass  :white_check_mark:
- [x ] I have added a new test case for someone to implement  :new:
- [x ] I have created an issue for my new test case  :speak_no_evil:
- [ x] I've :star: the repository (or not, all up to you)
- [ x] And more importantly, I've had fun! :beer:

### CODE REVIEW

**Comment by xstplvivek** [comment]
I have modified 2 test cases as I found out they were wrong.

**Comment by xstplvivek** [comment]
I have modified 2 test cases as I found they were wrong.

**Comment by xstplvivek** [comment]
Here are the 2 test cases I fixed:
```
// below test case specifies 13.37km/h but it passes 13.37m/s, which is wrong
it('F = 13N, t=7s w = 1kg, v = 13.37km/h should have 94.71m/s as final speed.', () => {
    // expect(findVFinal("13N", "7s", "1kg", "13.37m/s")).toBe("94.71m/s");
    expect(findVFinal("13N", "7s", "1kg", "13.37km/h")).toBe("94.71m/s");
  });

```
```
// here expected output is 0.3m.s but is actually checked with 0.2m/s
  it('F = 10N, t=1s w = 100kg, v = 0.2m/s should have 0.3m/s as final speed.', () => {
    // expect(findVFinal("10N", "1s", "100kg", "0.2m/s")).toBe("0.2m/s");
    expect(findVFinal("10N", "1s", "100kg", "0.2m/s")).toBe("0.3m/s");
  });
```

**Comment by rgehan** [comment]
Hey @xstplvivek,

Thanks for your contribution, your PR was merged, and your kata is now available for others to play with.

If there's been any issue with the process, please ping me in your reply.

##### This comment was automatically generated by a bot.

**Pull request merged**
