### PR TITLE
Implement isEmpty

### PR DESCRIPTION
**Pull request by leventdeniz**
## Details
**Issue you fixed:** #731 

**Issue you added:** #739 

**Name of the function you implemented**: isEmpty

**Name of the function you added test cases for**: isEuro

## Checklist (won't be merged if they are not all ticked)
- [x] I have asked for this issue, and was assigned it
- [x] I have properly filled the "Details" section above  :arrow_up:
- [x] I didn't modify any test case  :red_circle:
- [x] I have implemented the function and all its tests pass  :white_check_mark:
- [x] I have added a new test case for someone to implement  :new:
- [x] I have created an issue for my new test case  :speak_no_evil:
- [ ] I've :star: the repository (or not, all up to you)
- [x] And more importantly, I've had fun! :beer:

### CODE REVIEW

**Comment by leventdeniz** [comment]
I'confused, this should work but it doesn't. What am I doing wrong?

**Comment by leventdeniz** [comment]
Ok so the tests were not exactly wrong but instead of for example `expect(isEmpty([])).toBeTruthy();` it was `expect(isEmpty([]).toBeTruthy());`.
That's why the initial tests failed.

**Comment by rgehan** [comment]
Hey @leventdeniz,

Thanks for your contribution, your PR was merged, and your kata is now available for others to play with.

If there's been any issue with the process, please ping me in your reply.

##### This comment was automatically generated by a bot.

**Pull request merged**
