### PR TITLE
implemented mean

### PR DESCRIPTION
**Pull request by ivansieder**
### Details
**Link to the issue:** https://github.com/rgehan/hacktoberfest-2k18-katas/issues/33

**Name of the function you implemented**: Mean

**Name of the function you added test cases for**: mean

### Checklist
- [x] I have asked for this issue, and was assigned it
- [x] I have properly filled the "Details" section above  :arrow_up:
- [x] I didn't modify any test case  :red_circle:
- [x] I have implemented the function and all its tests pass  :white_check_mark:
- [x] I have added a new test case for someone to implement  :new:
- [x] I have created an issue for my new test case  :speak_no_evil:
- [x] And more importantly, I've had fun! :beer:

### CODE REVIEW

**Comment by cptjacky** [comment]
Hey, you need to create a new test case before we can merge this! :)

**Comment by rgehan** [comment]
@ivansieder Do you plan to complete it, or should I give the issue to someone else?

**Comment by ivansieder** [comment]
@rgehan done, added another challenge!

**Comment by rgehan** [comment]
Just remove your changes on `yarn.lock` so I can merge it :)

**Comment by rgehan** [comment]
Did it manually, I'll merge it :)

**Pull request merged**
