### PR TITLE
Implemented PrimeFactors

### PR DESCRIPTION
**Pull request by lourdesr**
## Details
**Link to the issue:** *[#161](https://github.com/rgehan/hacktoberfest-2k18-katas/issues/161)*

**Name of the function you implemented**: *primeFactors*

**Name of the function you added test cases for**: *largestString*

## Checklist (won't be merged if they are not all ticked)
- [x] I have asked for this issue, and was assigned it
- [x] I have properly filled the "Details" section above  :arrow_up:
- [x] I didn't modify any test case  :red_circle:
- [x] I have implemented the function and all its tests pass  :white_check_mark:
- [x] I have added a new test case for someone to implement  :new:
- [x] I have created an issue for my new test case  :speak_no_evil:
- [x] I've :star: the repository (or not, all up to you)
- [x] And more importantly, I've had fun! :beer:

### CODE REVIEW

**Comment by rgehan** [comment]
Could you implement it without changing the original test?

**Comment by lourdesr** [comment]
Yeah, sure thing. Just give me a few mins.

**Comment by lourdesr** [comment]
Hey @rgehan - Kept the tests how it was before.

**Comment by rgehan** [comment]
You should have left the `toBeEqual -> toEqual` change, I was asking you to remove the changes you made to the actual parameters.

It's your implementation that should comply to the test, not the opposite (except very obvious errors)

**Comment by lourdesr** [comment]
Um, I did not make any changed to the parameters in the tests. The only change I made was from `toBeEqual` to `toEqual`. I did this because Jest was saying `toBeEqual` isn't a function. 

Should I change it back to `toEqual` ?

**Comment by rgehan** [comment]
Oh my bad, yes, put `toEqual` back and we'll be fine :)

**Comment by lourdesr** [comment]
Done.
No worries! :)

**Pull request merged**
