### PR TITLE
implemented toBaseNine

### PR DESCRIPTION
**Pull request by andersou**
## Details
**Issue you fixed:** #505 

**Issue you added:** #513 

**Name of the function you implemented**: *toBaseNine*

**Name of the function you added test cases for**: *capitalizedWordCounter*

## Checklist (won't be merged if they are not all ticked)
- [x] I have asked for this issue, and was assigned it
- [x] I have properly filled the "Details" section above  :arrow_up:
- [x] I didn't modify any test case  :red_circle:
- [x] I have implemented the function and all its tests pass  :white_check_mark:
- [x] I have added a new test case for someone to implement  :new:
- [x] I have created an issue for my new test case  :speak_no_evil:
- [x] I've :star: the repository (or not, all up to you)
- [x] And more importantly, I've had fun! :beer:

### CODE REVIEW

**Comment by andersou** [comment]
> ## There's a problem with your PR
> Hey **Anderson Souza**,
> Please read the following log in order to understand what is the problem with
> your PR.
> 
> If there's an actual error, please fix it.
> 
> If you think this is a false-positive, or if you can justify your changes,
> please respond to this comment.
> 
> ### Node.js: node
> **./scripts/test.js**
> 
> ```
> ###################################
> ##           WARNING             ##
> ###################################
> 
> It looks like you have changed more than 3 files in this PR. Could you
> check that you only committed relevant files. For example, any file
> outputted by your IDE, or by a build tool you use is not relevant. On
> the other hand, if you fixed a test case, then it's ok.
> 
> Here are the files that you changed:
> - src/capitalizedWordCounter.js (NEW)
> - src/capitalizedWordCounter.test.js (NEW)
> - src/toBaseNine.js (MODIFIED)
> - src/toBaseNine.test.js (MODIFIED)
> 
> ###################################
> ##     LINTING YOUR CHANGES      ##
> ###################################
> 
> Running command: "eslint src/capitalizedWordCounter.js src/capitalizedWordCounter.test.js src/toBaseNine.js src/toBaseNine.test.js"
> 
> ###################################
> ##       RUNNING TEST FILE       ##
> ###################################
> 
> Running command: "jest src/toBaseNine.test.js"
> 
>  PASS  src/toBaseNine.test.js
>   toBaseNine
>     ✓ toBaseNine should return a base-9 value of the base-10 input (4ms)
>     ✓ toBaseNine should return a base-9 value of the base-10 input
>     ✓ toBaseNine should return a base-9 value of the base-10 input (1ms)
>     ✓ toBaseNine should return a base-9 value of the base-10 input
> 
> Test Suites: 1 passed, 1 total
> Tests:       4 passed, 4 total
> Snapshots:   0 total
> Time:        1.288s
> Ran all test suites matching /src\/toBaseNine.test.js/i.
> Exiting with status: 1
> ```

No linter errors and all tests passed.
Did this happen because I corrected the test error?

**Comment by rgehan** [comment]
@andersou I only allow self-merge for PRs that have only the required number of changes.

When you have to fix the tests, I merge the PR myself because sometimes the change is not justified.

In you case it's ok.

**Comment by rgehan** [comment]
Hey @andersou,

Thanks for your contribution, your PR was merged, and your kata is now available for others to play with.

If there's been any issue with the process, please ping me in your reply.

##### This comment was automatically generated by a bot.

**Pull request merged**
