### PR TITLE
implement sum of products

### PR DESCRIPTION
**Pull request by KumarManoj-S**

### CODE REVIEW

**Comment by KumarManoj-S** [comment]
I have added files for new implementation.

**Comment by rgehan** [comment]
Hey @KumarManoj-S,

We cannot let you merge your PR as it seems you weren't assigned to the issue, or it simply doesn't exist.

Please double-check you provided the correct issue ID.

If you think this is a mistake, feel free to ping me in your reply.

##### This comment was automatically generated by a bot.

**Comment by rgehan** [comment]
The whole repo is automated, I cannot manually keep track of everyone sorry, please use `/request` the next time you want an issue to be assigned to you

**Pull request closed without merging**
