### PR TITLE
implemented 'get', added test for 'fill' and created new issue

### PR DESCRIPTION
**Pull request by kumaran-14**
fill

### Details
**Link to the issue:** *https://github.com/rgehan/hacktoberfest-2k18-katas/issues/21*

**Name of the function you implemented**: *get*

**Name of the function you added test cases for**: *fill*

### Checklist
- [x] I have asked for this issue, and was assigned it
- [x] I have properly filled the "Details" section above  :arrow_up:
- [x] I didn't modify any test case  :red_circle:
- [x] I have implemented the function and all its tests pass  :white_check_mark:
- [x] I have added a new test case for someone to implement  :new:
- [x] I have created an issue for my new test case  :speak_no_evil:
- [x] And more importantly, I've had fun! :beer:

### CODE REVIEW

**Comment by kumaran-14** [comment]
Can you elaborate more?

**Comment by kumaran-14** [comment]
@rgehan  @TimothePearce What should i use? ..toStrictEqual, ..toEqual or toBeTruthy?

**Comment by TimothePearce** [comment]
`toEqual()` seems good here, @rgehan will do your review

**Comment by rgehan** [comment]
Cool PR!

**Pull request merged**
