### PR TITLE
Implement removeConsecutiveDuplicates (fix #45)

### LINKED ISSUE #45: Implement 'removeConsecutiveDuplicates'
### Name of the function

**Where to implement**: `src/removeConsecutiveDuplicates.js`
**Where are the tests**: `src/removeConsecutiveDuplicates.test.js`
**Description**:
Remove all consecutive duplicate values from an array

Thanks :heart:

### PR DESCRIPTION
**Pull request by piksu**
### Details
**Link to the issue:** #45 

**Name of the function you implemented**: removeConsecutiveDuplicates: (array: any)

**Name of the function you added test cases for**: -

### Checklist
- [x] I have asked for this issue, and was assigned it
- [X] I have properly filled the "Details" section above  :arrow_up:
- [X] I didn't modify any test case  :red_circle:
- [X] I have implemented the function and all its tests pass  :white_check_mark:
- [x] I have added a new test case for someone to implement  :new:
- [ ] I have created an issue for my new test case  :speak_no_evil:
- [X] I've :star: the repository (or not, all up to you)
- [X] And more importantly, I've had fun! :beer:

### CODE REVIEW

**Comment by rgehan** [comment]
You need to add a new kata too

**Comment by rgehan** [comment]
Closed as this still isn't fixed, sorry

**Comment by rgehan** [comment]
@piksu Reopened it :)

**Comment by rgehan** [comment]
If TravisBuddy's happy, I'm happy. Good job!

@piksu Could you create an issue for your new kata?

**Comment by piksu** [comment]
Thanks!

@rgehan I've created a new issue and it can be found here: https://github.com/rgehan/hacktoberfest-2k18-katas/issues/174

**Comment by rgehan** [comment]
Cool thanks!

**Pull request merged**
