### PR TITLE
Implements multiplication

### PR DESCRIPTION
**Pull request by chgasparoto**
Multiplication :+1:

### CODE REVIEW

**Comment by chgasparoto** [comment]
For #5

**Comment by TimothePearce** [comment]
the purpose of the kata is not to modify the tests in your way.

**Comment by cptjacky** [comment]
No news for a few hours and missing a few things.

I'm releasing that issue for someone else to take, sorry.

**Comment by chgasparoto** [comment]
No problem, I did in my lunch time! I'll look for mode :)

**Pull request closed without merging**
