### PR TITLE
Feature count code lines

### PR DESCRIPTION
**Pull request by mannutech**
## Details
**Link to the issue:** *https://github.com/rgehan/hacktoberfest-2k18-katas/issues/157*

**Name of the function you implemented**: *countCodeLines*

**Name of the function you added test cases for**: *countCodeLines*

## Checklist (won't be merged if they are not all ticked)
- [x] I have asked for this issue, and was assigned it
- [x] I have properly filled the "Details" section above  :arrow_up:
- [x] I didn't modify any test case  :red_circle:
- [x] I have implemented the function and all its tests pass  :white_check_mark:
- [x] I have added a new test case for someone to implement  :new:
- [x] I have created an issue for my new test case  :speak_no_evil:
- [x] I've :star: the repository (or not, all up to you)
- [x] And more importantly, I've had fun! :beer:

### CODE REVIEW

**Comment by mannutech** [comment]
@rgehan Implemented hand written approach without using npm package

**Comment by mannutech** [comment]
@rgehan It may require a manual acceptance, as there was an issue with one of the earlier to initial pull.

**Comment by rgehan** [comment]
There are a few issues here:
- Why did you modify the test file for `countCodeLines`? You're only supposed to worry about the implementation, not the test cases
- You need to add a new kata (that's why TravisBuddy is complaining)

**Comment by mannutech** [comment]
@rgehan SHould I close this one.

**Comment by rgehan** [comment]
No, you can continue on this PR

**Pull request closed without merging**
