### PR TITLE
Implement trailingZeroes and add matrixTrace and runBrainfuck

### PR DESCRIPTION
**Pull request by Zeroji**
## Details
**Issue you fixed:** #518 

**Issue you added:** *link to the issue*

**Name of the function you implemented**: trailingZeroes

**Name of the function you added test cases for**: matrixTrace and runBrainfuck

## Checklist (won't be merged if they are not all ticked)
- [x] I have asked for this issue, and was assigned it
- [x] I have properly filled the "Details" section above  :arrow_up:
- [x] I didn't modify any test case  :red_circle:
- [x] I have implemented the function and all its tests pass  :white_check_mark:
- [x] I have added a new test case for someone to implement  :new:
- [x] I have created an issue for my new test case  :speak_no_evil:
- [x] I have added another new test case for some hard worker to implement :muscle: 
- [x] I've :star: the repository (or not, all up to you)
- [x] And more importantly, I've had fun! :beer:

### CODE REVIEW

**Comment by Zeroji** [comment]
> For a Pull Request to be considered, it needs at least 3 things:
> - A modified file, containing your implementation of the Kata.
> - A new file containing the tests for your new Kata idea.
> - An empty file, where someone will implement your new Kata idea.
> 
> Yours only has:
> - 1 modified implementations (needs 1)
> - 2 new implementations (needs 1)
> - 2 new test file (needs 1)
> ```

I have willingly and knowingly added two new test files instead of one, in an effort to increase the number of available issues for people to implement. When I requested issue #518 there were only two non-grabbed issues, so I felt adding some more would be a good idea.

Let me know if this isn't the right procedure, I haven't found additional information for this case.

**Comment by DanielRamosAcosta** [comment]
Can you create an Issue for the Brainfuck one? I would love to do it

**Comment by Zeroji** [comment]
> Can you create an Issue for the Brainfuck one? I would love to do it

Working on it right now.. and here it goes #524
Hopefully my duplicate kata issue is fixed soon and you get to grab it first

**Comment by DanielRamosAcosta** [comment]
Humm yes... it seems like I have to wait until this PR is merged 😢

**Comment by ArfatSalman** [comment]
@DanielRamosAcosta In your `matrixTrace` question, is this test case correct? 
```js
expect(matrixTrace([1, 2, 3, 4], [5, 6, 7, 8], [-8, -7, -6, -5], [-4, -3, -2, -1])).toEqual(0);
```

Should all the parameters be passed in an array? Or the test is intentionally like that?

Thanks

**Comment by DanielRamosAcosta** [comment]
@ArfatSalman that isn't my test, is @Zeroji one, but he already answered you 😉

**Pull request merged**
