### PR TITLE
fix stopApologizing

### PR DESCRIPTION
**Pull request by showmeyourhits**
## Details
**Issue you fixed:** #960 

**Issue you added:** #1084 

**Name of the function you implemented**: foobar

**Name of the function you added test cases for**: barbaz

## Checklist (won't be merged if they are not all ticked)
- [x] I have asked for this issue, and was assigned it
- [x] I have properly filled the "Details" section above  :arrow_up:
- [x] I didn't modify any test case  :red_circle:
- [x] I have implemented the function and all its tests pass  :white_check_mark:
- [x] I have added a new test case for someone to implement  :new:
- [x] I have created an issue for my new test case  :speak_no_evil:
- [x] I've :star: the repository (or not, all up to you)
- [x] And more importantly, I've had fun! :beer:

### CODE REVIEW

**Comment by showmeyourhits** [comment]
There was a problem with test: bracket was missplaced - i fixed it.

**Comment by showmeyourhits** [comment]
> ## There's a problem with your PR
> Hey **Ozhigin Alexander Sergeevich**,
> Please read the following log in order to understand what is the problem with
> your PR.
> 
> If there's an actual error, please fix it.
> 
> If you think this is a false-positive, or if you can justify your changes,
> please respond to this comment.
> 
> ### Node.js: node
> **./scripts/test.js**
> 
> ```
> ###################################
> ##           WARNING             ##
> ###################################
> 
> It looks like you have changed more than 3 files in this PR. Could you
> check that you only committed relevant files. For example, any file
> outputted by your IDE, or by a build tool you use is not relevant. On
> the other hand, if you fixed a test case, then it's ok.
> 
> Here are the files that you changed:
> - src/stopApologizing.js (MODIFIED)
> - src/stopApologizing.test.js (MODIFIED)
> - src/stopSwearing.js (NEW)
> - src/stopSwearing.test.js (NEW)
> 
> ###################################
> ##     LINTING YOUR CHANGES      ##
> ###################################
> 
> Running command: "eslint src/stopApologizing.js src/stopApologizing.test.js src/stopSwearing.js src/stopSwearing.test.js"
> 
> ###################################
> ##       RUNNING TEST FILE       ##
> ###################################
> 
> Running command: "jest src/stopApologizing.test.js"
> 
>  PASS  src/stopApologizing.test.js
>   stopApologizing
>     ✓ converts apologies to appreciative thanks (4ms)
> 
> Test Suites: 1 passed, 1 total
> Tests:       1 passed, 1 total
> Snapshots:   0 total
> Time:        1.14s
> Ran all test suites matching /src\/stopApologizing.test.js/i.
> Exiting with status: 1
> ```

There was a problem with test: missplaced bracket - i fixed it.

**Comment by rgehan** [comment]
Hey @showmeyourhits,

Thanks for your contribution, your PR was merged, and your kata is now available for others to play with.

If there's been any issue with the process, please ping me in your reply.

##### This comment was automatically generated by a bot.

**Pull request merged**
