### PR TITLE
Implement reverseNumber

### PR DESCRIPTION
**Pull request by Banb4n**
## Details
**Issue you fixed:** #301 

**Issue you added:** #309

**Name of the function you implemented**: *reverseNumber*

**Name of the function you added test cases for**: *isGroupByPair*

## Checklist (won't be merged if they are not all ticked)
- [x] I have asked for this issue, and was assigned it
- [x] I have properly filled the "Details" section above  :arrow_up:
- [x] I didn't modify any test case  :red_circle:
- [x] I have implemented the function and all its tests pass  :white_check_mark:
- [x] I have added a new test case for someone to implement  :new:
- [x] I have created an issue for my new test case  :speak_no_evil:
- [x] I've :star: the repository (or not, all up to you)
- [x] And more importantly, I've had fun! :beer:

### CODE REVIEW

**Comment by rgehan** [comment]
^ Fixed it for you

**Comment by rgehan** [comment]
@Banb4n Du coup si tu pouvais tester le petit script de self-merge juste au dessus, ça me ferai très plaisir :)

**Comment by Banb4n** [comment]
Avec plaisir 😉

**Comment by rgehan** [comment]
Hey @Banb4n,

Thanks for your contribution, your PR was merged, and your kata is now available for others to play with.

If there's been any issue with the process, please ping me in your reply.

##### This comment was automatically generated by a bot.

**Comment by rgehan** [comment]
Cool 🎉

**Comment by Banb4n** [comment]
Nice 👌 🎉

**Pull request merged**
