### PR TITLE
Implementation of countCodeLines

### PR DESCRIPTION
**Pull request by mannutech**
## Details
**Link to the issue:** *https://github.com/rgehan/hacktoberfest-2k18-katas/issues/157*

**Name of the function you implemented**: *countCodeLines*

**Name of the function you added test cases for**: *countCodeLines*

## Checklist (won't be merged if they are not all ticked)
- [x] I have asked for this issue, and was assigned it
- [x] I have properly filled the "Details" section above  :arrow_up:
- [x] I didn't modify any test case  :red_circle:
- [x] I have implemented the function and all its tests pass  :white_check_mark:
- [x] I have added a new test case for someone to implement  :new:
- [x] I have created an issue for my new test case  :speak_no_evil:
- [x] I've :star: the repository (or not, all up to you)
- [x] And more importantly, I've had fun! :beer:

### CODE REVIEW

**Comment by rgehan** [comment]
@mannutech We want to do all this without using any npm package, you'll have to do it by hand sorry!

**Comment by mannutech** [comment]
@rgehan I think I have got it correctly at my end and the issue was assigned to me as well but after some re-assignment. Can you check this manually.

**Comment by mannutech** [comment]
@rgehan You should have mentioned this in the details.

**Comment by rgehan** [comment]
It's (or was) somewhere in the rules

**Comment by mannutech** [comment]
@rgehan Now you should accept it ideally . Should I reopen

**Comment by rgehan** [comment]
@mannutech If you're ok with doing it without a package yep

**Pull request closed without merging**
