### PR TITLE
Added case for Min, and test suites.

### PR DESCRIPTION
**Pull request by audrius59**
### Details
**Link to the issue:** *https://github.com/rgehan/hacktoberfest-2k18-katas/issues/30#issuecomment-426333662*

Name of the function you implemented:**Min**

Name of the function you added test cases for:**PinValidator**

### Checklist
- [x] I have asked for this issue, and was assigned it
- [x] I have properly filled the "Details" section above  :arrow_up:
- [x] I didn't modify any test case  :red_circle:
- [x] I have implemented the function and all its tests pass  :white_check_mark:
- [x] I have added a new test case for someone to implement  :new:
- [x] I have created an issue for my new test case  :speak_no_evil:
- [x] And more importantly, I've had fun! :beer:

### CODE REVIEW

**Comment by TimothePearce** [comment]
You should rebase your repository, your PR has some conflicting files

**Comment by cptjacky** [comment]
Hey,

The `multiply` function has already been assigned to someone else, you'll have to remove your implementation from this PR :) 

You also have to create a new test case for someone else to implement (be creative, and take a look at the README for more info!).

**Comment by rgehan** [comment]
Could you add back the original `multiply` file, you're completely removing it here.

You should also create a new test case for someone to implement, see the README

**Comment by audrius59** [comment]
> Could you add back the original `multiply` file, you're completely removing it here.
> 
> You should also create a new test case for someone to implement, see the README

I have creatednew test case pinValidator, but having trouble with adding back original multiply.js file. Should I create new pull request for it?

**Comment by rgehan** [comment]
I'll fix it after it's merged don't worry

**Pull request merged**
