### PR TITLE
implement isDollar

### PR DESCRIPTION
**Pull request by aprex**
## Details
**Issue you fixed:** #509 

**Issue you added:** #549 

**Name of the function you implemented**: isDollar

**Name of the function you added test cases for**: map

## Checklist (won't be merged if they are not all ticked)
- [x] I have asked for this issue, and was assigned it
- [x] I have properly filled the "Details" section above  :arrow_up:
- [x] I didn't modify any test case  :red_circle:
- [x] I have implemented the function and all its tests pass  :white_check_mark:
- [x] I have added a new test case for someone to implement  :new:
- [x] I have created an issue for my new test case  :speak_no_evil:
- [x] I've :star: the repository (or not, all up to you)
- [x] And more importantly, I've had fun! :beer:

### CODE REVIEW

**Comment by rgehan** [comment]
@aprex Please mention in your new issue not to use `Array.map`

**Comment by aprex** [comment]
@rgehan yes, I added some description

**Comment by aprex** [comment]
> Hey @aprex,
> It looks like your PR fulfills all the necessary criterias.
> 
> Merge your PR by replying `/merge fixed:#XXX created:#YYY` to this message, with:
> 
> * `XXX` the ID of the issue you were assigned
> * `YYY` the ID of the issue you created for you new kata
> 
> ###### TravisBuddy Request Identifier: b29b53c0-cc64-11e8-9706-8d7bf71fb7b5

/merge fixed:#509 created:#549

**Comment by rgehan** [comment]
Hey @aprex,

Thanks for your contribution, your PR was merged, and your kata is now available for others to play with.

If there's been any issue with the process, please ping me in your reply.

##### This comment was automatically generated by a bot.

**Pull request merged**
