### PR TITLE
Implemented countCodeLines changes.

### PR DESCRIPTION
**Pull request by mannutech**
## Details
**Link to the issue:** *https://github.com/rgehan/hacktoberfest-2k18-katas/issues/157*

**Name of the function you implemented**: *countCodeLines*

**Name of the function you added test cases for**: *decimalToOctal*

## Checklist (won't be merged if they are not all ticked)
- [x] I have asked for this issue, and was assigned it
- [x] I have properly filled the "Details" section above  :arrow_up:
- [x] I didn't modify any test case  :red_circle:
- [x] I have implemented the function and all its tests pass  :white_check_mark:
- [x] I have added a new test case for someone to implement  :new:
- [x] I have created an issue for my new test case  :speak_no_evil:
- [x] I've :star: the repository (or not, all up to you)
- [x] And more importantly, I've had fun! :beer:

### CODE REVIEW

**Comment by mannutech** [comment]
@rgehan I have asked you several times, Please look for the countCodeLines.test.js file to have the assertions be correct. I have raised this for more than 5 times, travis is failing my pr repeatedly. DO somehting this time. 
Line number 35 assertion can never be equal to 5 . Please look into this

**Comment by mannutech** [comment]
@rgehan Whosoever has written this test case missed out on the function call inside the assertion.

**Comment by rgehan** [comment]
I don't like your attitude. If you know where the issue is, then why don't you fix it?

This is not my full-time job, and I'm not at your disposal.

**Comment by mannutech** [comment]
@rgehan My dear travis is failing my PR when I do multiple changes to more than one file.

**Comment by mannutech** [comment]
@rgehan I kindly request you to help me push the change in the main file.

**Comment by rgehan** [comment]
If for some reason there's an error in the test case, you're allowed to fix it. I can still merge it if I deem your PR correct.

Please watch your attitude in the future.

**Comment by mannutech** [comment]
@rgehan you can take a look buddy.

**Pull request merged**
